export const apiUrl = 'http://localhost:9090'
export const statusUnassigned = 'UNASSIGNED'
export const statusAssigned = 'ASSIGNED'
export const statusOpen = 'OPEN'
export const statusClosed = 'CLOSED'
export const variationIssueAssigned = 'info'
export const variationIssueUnassigned = 'primary'
export const variationIssueOpen = 'secondary'
export const variationIssueClosed = 'dark'
export const variationIssueOther = 'secondary'
export const variationMessageNoReply = 'info'
export const variationMessageReply = 'info'

